M48
; DRILL file {KiCad (6.0.1)} date Mon Aug 15 17:42:42 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-15T17:42:42+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.4768Y-3.6378
X5.7043Y-3.6378
T2
X6.1417Y-3.2441
T3
X4.7244Y-2.5197
X4.7244Y-3.0709
X6.4567Y-2.5197
X6.4567Y-3.0709
T0
M30
